<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
          {
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"用户管理",
                      "menuJump":"列表",
                      "tableName":"yonghu"
                  }
              ],
              "menu":"用户管理"
          }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"面试通知管理",
                        "menuJump":"列表",
                        "tableName":"mianshitongzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"面试通知收藏管理",
                        "menuJump":"列表",
                        "tableName":"mianshitongzhiCollection"
                    }
                ],
                "menu":"面试通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学习资源管理",
                        "menuJump":"列表",
                        "tableName":"xuexizhiyuan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"学习资源收藏管理",
                        "menuJump":"列表",
                        "tableName":"xuexizhiyuanCollection"
                    }
                ],
                "menu":"学习资源管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资料文档管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaowendang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"资料文档收藏管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaowendangCollection"
                    }
                ],
                "menu":"资料文档管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
							"新增",
							"修改",
			                "删除"
			            ],
			            "menu":"资源分类管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryXuexizhiyuan"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
			,
			{
			     "child":[
			         {
			             "buttons":[
			                 "查看",
			                 "新增",
			                 "修改",
			                 "删除"
			             ],
			             "menu":"轮播图管理",
			             "menuJump":"列表",
			             "tableName":"config"
			         }
			     ],
			     "menu":"轮播图管理"
			 }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"面试通知管理",
                        "menuJump":"列表",
                        "tableName":"mianshitongzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"面试通知收藏管理",
                        "menuJump":"列表",
                        "tableName":"mianshitongzhiCollection"
                    }
                ],
                "menu":"面试通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学习资源管理",
                        "menuJump":"列表",
                        "tableName":"xuexizhiyuan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"学习资源收藏管理",
                        "menuJump":"列表",
                        "tableName":"xuexizhiyuanCollection"
                    }
                ],
                "menu":"学习资源管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资料文档管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaowendang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"资料文档收藏管理",
                        "menuJump":"列表",
                        "tableName":"zhiliaowendangCollection"
                    }
                ],
                "menu":"资料文档管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"学生",
        "tableName":"yonghu"
    }
	,
	{
	    "backMenu":[
	      {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"面试通知管理",
	                    "menuJump":"列表",
	                    "tableName":"mianshitongzhi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"面试通知收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"mianshitongzhiCollection"
	                }
	            ],
	            "menu":"面试通知管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"学习资源管理",
	                    "menuJump":"列表",
	                    "tableName":"xuexizhiyuan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"学习资源收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"xuexizhiyuanCollection"
	                }
	            ],
	            "menu":"学习资源管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"资料文档管理",
	                    "menuJump":"列表",
	                    "tableName":"zhiliaowendang"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"资料文档收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"zhiliaowendangCollection"
	                }
	            ],
	            "menu":"资料文档管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"老师",
	    "tableName":"laoshi"
	}
];

var hasMessage = '';
